// Site chrome strings — everything around the book's own content: header
// nav, the picker bar's labels, breadcrumbs, pagination, the footer, and the
// error page. The book's content itself is translated per-locale in
// content/<locale>/…; this is the much smaller set of UI strings the site
// itself owns.
//
// The four English locales (en-gb, en-us, en-gb-oxendict, en-001) share one
// table: none of these short UI strings has a US/UK/Oxford spelling
// difference. Arabic (ar-001), Welsh (cy-001), German (de-de), Japanese (ja-jp), Chinese (zh-cn), Spanish
// (es-001), French (fr-001), and Hindi (hi-in) each need their own.

const en = {
	siteBrand: 'Digital Health Guide',
	skipToMain: 'Skip to main content',
	siteHeader: 'Site header',
	mainNav: 'Main',
	navContents: 'Contents',
	navGlossary: 'Glossary',
	navIndex: 'Index',
	navStyleGuide: 'Style guide',
	navSpecification: 'Specification',
	navGitHub: 'GitHub',
	pickerTheme: 'Theme',
	pickerLocale: 'Language',
	pickerTextSize: 'Text size',
	pickerShare: 'Share',
	pickerShareCopyLink: 'Copy link',
	pickerShareCopied: 'Copied',
	breadcrumb: 'Breadcrumb',
	breadcrumbChapters: 'Chapters',
	breadcrumbReference: 'Reference',
	onThisPage: 'On this page',
	headingAnchorPrefix: 'Link to',
	chapterNavigation: 'Chapter navigation',
	previous: 'Previous',
	next: 'Next',
	editOnGitHub: 'Edit this page on GitHub',
	sourceOfTruth: 'the book is the source of truth; this site renders it.',
	siteFooter: 'Site footer',
	footerDescription:
		'a practical handbook of best practices for delivering digital services in health and social care organizations. Written by Joel Parker Henderson. Built with the',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'Specification',
	notFoundHeading: 'Page not found',
	errorHeading: 'Something went wrong',
	notFoundBody: 'There is no page at',
	notFoundBodyEnd: 'The book may have moved or renamed it.',
	errorBodyFallback: 'The page could not be loaded.',
	tryPrefix: 'Try the',
	tryTableOfContents: 'contents',
	tryGlossary: 'glossary',
	tryOr: 'or the',
	tryIndex: 'index'
};

const ar = {
	siteBrand: 'دليل الصحة الرقمية',
	skipToMain: 'الانتقال إلى المحتوى الرئيسي',
	siteHeader: 'رأس الموقع',
	mainNav: 'التنقل الرئيسي',
	navContents: 'المحتويات',
	navGlossary: 'المسرد',
	navIndex: 'الفهرس',
	navStyleGuide: 'دليل الأسلوب',
	navSpecification: 'المواصفات',
	navGitHub: 'GitHub',
	pickerTheme: 'السمة',
	pickerLocale: 'اللغة',
	pickerTextSize: 'حجم النص',
	pickerShare: 'مشاركة',
	pickerShareCopyLink: 'نسخ الرابط',
	pickerShareCopied: 'تم النسخ',
	breadcrumb: 'مسار التنقل',
	breadcrumbChapters: 'الفصول',
	breadcrumbReference: 'المرجع',
	onThisPage: 'في هذه الصفحة',
	headingAnchorPrefix: 'رابط إلى',
	chapterNavigation: 'التنقل بين الفصول',
	previous: 'السابق',
	next: 'التالي',
	editOnGitHub: 'تعديل هذه الصفحة على GitHub',
	sourceOfTruth: 'الكتاب هو مصدر الحقيقة؛ هذا الموقع يعرضه.',
	siteFooter: 'تذييل الموقع',
	footerDescription:
		'دليل عملي لأفضل الممارسات في تقديم الخدمات الرقمية في مؤسسات الصحة والرعاية الاجتماعية. كتبه Joel Parker Henderson. بُني باستخدام',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'المواصفات',
	notFoundHeading: 'الصفحة غير موجودة',
	errorHeading: 'حدث خطأ ما',
	notFoundBody: 'لا توجد صفحة في',
	notFoundBodyEnd: 'ربما يكون الكتاب قد نقلها أو غيّر اسمها.',
	errorBodyFallback: 'تعذّر تحميل الصفحة.',
	tryPrefix: 'جرّب',
	tryTableOfContents: 'المحتويات',
	tryGlossary: 'المسرد',
	tryOr: 'أو',
	tryIndex: 'الفهرس'
};

const cyGb = {
	siteBrand: 'Digital Health Guide',
	skipToMain: 'Neidio i’r prif gynnwys',
	siteHeader: 'Pennawd y wefan',
	mainNav: 'Prif lywio',
	navContents: 'Cynnwys',
	navGlossary: 'Geirfa',
	navIndex: 'Mynegai',
	navStyleGuide: 'Canllaw arddull',
	navSpecification: 'Manyleb',
	navGitHub: 'GitHub',
	pickerTheme: 'Thema',
	pickerLocale: 'Iaith',
	pickerTextSize: 'Maint testun',
	pickerShare: 'Rhannu',
	pickerShareCopyLink: 'Copïo’r ddolen',
	pickerShareCopied: 'Wedi copïo',
	breadcrumb: 'Briwsion bara',
	breadcrumbChapters: 'Penodau',
	breadcrumbReference: 'Cyfeirnod',
	onThisPage: 'Ar y dudalen hon',
	headingAnchorPrefix: 'Dolen i',
	chapterNavigation: 'Llywio penodau',
	previous: 'Blaenorol',
	next: 'Nesaf',
	editOnGitHub: 'Golygu’r dudalen hon ar GitHub',
	sourceOfTruth: 'y llyfr yw’r ffynhonnell wirionedd; mae’r wefan hon yn ei rendro.',
	siteFooter: 'Troedyn y wefan',
	footerDescription:
		'llawlyfr ymarferol o arferion gorau ar gyfer cyflenwi gwasanaethau digidol mewn sefydliadau iechyd a gofal cymdeithasol. Ysgrifennwyd gan Joel Parker Henderson. Adeiladwyd gyda’r',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'Manyleb',
	notFoundHeading: 'Heb ganfod y dudalen',
	errorHeading: 'Aeth rhywbeth o’i le',
	notFoundBody: 'Nid oes tudalen yn',
	notFoundBodyEnd: 'Mae’n bosibl bod y llyfr wedi symud neu ailenwi hon.',
	errorBodyFallback: 'Ni ellid llwytho’r dudalen.',
	tryPrefix: 'Rhowch gynnig ar y',
	tryTableOfContents: 'cynnwys',
	tryGlossary: 'eirfa',
	tryOr: 'neu’r',
	tryIndex: 'mynegai'
};

const zhCn = {
	siteBrand: '数字健康指南',
	skipToMain: '跳到主要内容',
	siteHeader: '网站页眉',
	mainNav: '主导航',
	navContents: '目录',
	navGlossary: '术语表',
	navIndex: '索引',
	navStyleGuide: '风格指南',
	navSpecification: '规范',
	navGitHub: 'GitHub',
	pickerTheme: '主题',
	pickerLocale: '语言',
	pickerTextSize: '字号',
	pickerShare: '分享',
	pickerShareCopyLink: '复制链接',
	pickerShareCopied: '已复制',
	breadcrumb: '面包屑导航',
	breadcrumbChapters: '章节',
	breadcrumbReference: '参考资料',
	onThisPage: '本页内容',
	headingAnchorPrefix: '链接到',
	chapterNavigation: '章节导航',
	previous: '上一页',
	next: '下一页',
	editOnGitHub: '在 GitHub 上编辑此页',
	sourceOfTruth: '本书是权威来源；本网站仅负责呈现。',
	siteFooter: '网站页脚',
	footerDescription:
		'一本关于在医疗与社会保健机构中交付数字服务最佳实践的实用手册。作者：Joel Parker Henderson。构建工具：',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: '规范',
	notFoundHeading: '页面未找到',
	errorHeading: '出现错误',
	notFoundBody: '没有页面位于',
	notFoundBodyEnd: '本书可能已移动或重命名该页面。',
	errorBodyFallback: '无法加载该页面。',
	tryPrefix: '请尝试',
	tryTableOfContents: '目录',
	tryGlossary: '术语表',
	tryOr: '或',
	tryIndex: '索引'
};

const es = {
	siteBrand: 'Guía de Salud Digital',
	skipToMain: 'Saltar al contenido principal',
	siteHeader: 'Encabezado del sitio',
	mainNav: 'Navegación principal',
	navContents: 'Contenido',
	navGlossary: 'Glosario',
	navIndex: 'Índice',
	navStyleGuide: 'Guía de estilo',
	navSpecification: 'Especificación',
	navGitHub: 'GitHub',
	pickerTheme: 'Tema',
	pickerLocale: 'Idioma',
	pickerTextSize: 'Tamaño del texto',
	pickerShare: 'Compartir',
	pickerShareCopyLink: 'Copiar enlace',
	pickerShareCopied: 'Copiado',
	breadcrumb: 'Ruta de navegación',
	breadcrumbChapters: 'Capítulos',
	breadcrumbReference: 'Referencia',
	onThisPage: 'En esta página',
	headingAnchorPrefix: 'Enlace a',
	chapterNavigation: 'Navegación de capítulos',
	previous: 'Anterior',
	next: 'Siguiente',
	editOnGitHub: 'Editar esta página en GitHub',
	sourceOfTruth: 'el libro es la fuente de la verdad; este sitio lo presenta.',
	siteFooter: 'Pie de página del sitio',
	footerDescription:
		'un manual práctico de buenas prácticas para prestar servicios digitales en organizaciones de salud y atención social. Escrito por Joel Parker Henderson. Construido con',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'Especificación',
	notFoundHeading: 'Página no encontrada',
	errorHeading: 'Algo salió mal',
	notFoundBody: 'No hay ninguna página en',
	notFoundBodyEnd: 'Es posible que el libro se haya movido o cambiado de nombre.',
	errorBodyFallback: 'No se pudo cargar la página.',
	tryPrefix: 'Prueba con el',
	tryTableOfContents: 'contenido',
	tryGlossary: 'glosario',
	tryOr: 'o el',
	tryIndex: 'índice'
};

const fr = {
	siteBrand: 'Guide de la santé numérique',
	skipToMain: 'Aller au contenu principal',
	siteHeader: 'En-tête du site',
	mainNav: 'Navigation principale',
	navContents: 'Sommaire',
	navGlossary: 'Glossaire',
	navIndex: 'Index',
	navStyleGuide: 'Guide de style',
	navSpecification: 'Spécification',
	navGitHub: 'GitHub',
	pickerTheme: 'Thème',
	pickerLocale: 'Langue',
	pickerTextSize: 'Taille du texte',
	pickerShare: 'Partager',
	pickerShareCopyLink: 'Copier le lien',
	pickerShareCopied: 'Copié',
	breadcrumb: 'Fil d’Ariane',
	breadcrumbChapters: 'Chapitres',
	breadcrumbReference: 'Référence',
	onThisPage: 'Sur cette page',
	headingAnchorPrefix: 'Lien vers',
	chapterNavigation: 'Navigation des chapitres',
	previous: 'Précédent',
	next: 'Suivant',
	editOnGitHub: 'Modifier cette page sur GitHub',
	sourceOfTruth: 'le livre est la source de vérité ; ce site le présente.',
	siteFooter: 'Pied de page du site',
	footerDescription:
		'un manuel pratique des bonnes pratiques pour livrer des services numériques dans les organisations de santé et d’action sociale. Écrit par Joel Parker Henderson. Construit avec le',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'Spécification',
	notFoundHeading: 'Page introuvable',
	errorHeading: 'Une erreur est survenue',
	notFoundBody: 'Il n’y a aucune page à',
	notFoundBodyEnd: 'Le livre l’a peut-être déplacée ou renommée.',
	errorBodyFallback: 'La page n’a pas pu être chargée.',
	tryPrefix: 'Essayez le',
	tryTableOfContents: 'sommaire',
	tryGlossary: 'glossaire',
	tryOr: 'ou l’',
	tryIndex: 'index'
};

const hi = {
	siteBrand: 'डिजिटल स्वास्थ्य मार्गदर्शिका',
	skipToMain: 'मुख्य सामग्री पर जाएं',
	siteHeader: 'साइट हेडर',
	mainNav: 'मुख्य नेविगेशन',
	navContents: 'सामग्री',
	navGlossary: 'शब्दावली',
	navIndex: 'सूचकांक',
	navStyleGuide: 'शैली मार्गदर्शिका',
	navSpecification: 'विनिर्देश',
	navGitHub: 'GitHub',
	pickerTheme: 'थीम',
	pickerLocale: 'भाषा',
	pickerTextSize: 'पाठ आकार',
	pickerShare: 'साझा करें',
	pickerShareCopyLink: 'लिंक कॉपी करें',
	pickerShareCopied: 'कॉपी किया गया',
	breadcrumb: 'ब्रेडक्रम्ब',
	breadcrumbChapters: 'अध्याय',
	breadcrumbReference: 'संदर्भ',
	onThisPage: 'इस पृष्ठ पर',
	headingAnchorPrefix: 'लिंक',
	chapterNavigation: 'अध्याय नेविगेशन',
	previous: 'पिछला',
	next: 'अगला',
	editOnGitHub: 'GitHub पर इस पृष्ठ को संपादित करें',
	sourceOfTruth: 'पुस्तक सत्य का स्रोत है; यह साइट इसे प्रस्तुत करती है।',
	siteFooter: 'साइट फ़ुटर',
	footerDescription:
		'स्वास्थ्य और सामाजिक देखभाल संगठनों में डिजिटल सेवाएं देने की सर्वोत्तम प्रथाओं की एक व्यावहारिक हैंडबुक। Joel Parker Henderson द्वारा लिखित। इसके साथ बनाया गया',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'विनिर्देश',
	notFoundHeading: 'पृष्ठ नहीं मिला',
	errorHeading: 'कुछ गलत हो गया',
	notFoundBody: 'यहां कोई पृष्ठ नहीं है',
	notFoundBodyEnd: 'हो सकता है पुस्तक ने इसे स्थानांतरित या पुनर्नामित किया हो।',
	errorBodyFallback: 'पृष्ठ लोड नहीं किया जा सका।',
	tryPrefix: 'कोशिश करें',
	tryTableOfContents: 'सामग्री',
	tryGlossary: 'शब्दावली',
	tryOr: 'या',
	tryIndex: 'सूचकांक'
};

const de = {
	siteBrand: 'Digital Health Guide',
	skipToMain: 'Zum Hauptinhalt springen',
	siteHeader: 'Kopfbereich der Website',
	mainNav: 'Hauptnavigation',
	navContents: 'Inhalt',
	navGlossary: 'Glossar',
	navIndex: 'Index',
	navStyleGuide: 'Styleguide',
	navSpecification: 'Spezifikation',
	navGitHub: 'GitHub',
	pickerTheme: 'Design',
	pickerLocale: 'Sprache',
	pickerTextSize: 'Textgröße',
	pickerShare: 'Teilen',
	pickerShareCopyLink: 'Link kopieren',
	pickerShareCopied: 'Kopiert',
	breadcrumb: 'Brotkrümelnavigation',
	breadcrumbChapters: 'Kapitel',
	breadcrumbReference: 'Referenz',
	onThisPage: 'Auf dieser Seite',
	headingAnchorPrefix: 'Link zu',
	chapterNavigation: 'Kapitelnavigation',
	previous: 'Zurück',
	next: 'Weiter',
	editOnGitHub: 'Diese Seite auf GitHub bearbeiten',
	sourceOfTruth: 'das Buch ist die Quelle der Wahrheit; diese Website stellt es dar.',
	siteFooter: 'Fußbereich der Website',
	footerDescription:
		'ein praxisnahes Handbuch bewährter Praktiken für die Erbringung digitaler Services in Organisationen des Gesundheits- und Sozialwesens. Geschrieben von Joel Parker Henderson. Erstellt mit dem',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: 'Spezifikation',
	notFoundHeading: 'Seite nicht gefunden',
	errorHeading: 'Etwas ist schiefgelaufen',
	notFoundBody: 'Unter',
	notFoundBodyEnd: 'gibt es keine Seite. Das Buch hat sie möglicherweise verschoben oder umbenannt.',
	errorBodyFallback: 'Die Seite konnte nicht geladen werden.',
	tryPrefix: 'Probieren Sie das',
	tryTableOfContents: 'Inhaltsverzeichnis',
	tryGlossary: 'Glossar',
	tryOr: 'oder den',
	tryIndex: 'Index'
};

const ja = {
	siteBrand: 'Digital Health Guide',
	skipToMain: 'メインコンテンツへスキップ',
	siteHeader: 'サイトヘッダー',
	mainNav: 'メインナビゲーション',
	navContents: '目次',
	navGlossary: '用語集',
	navIndex: '索引',
	navStyleGuide: 'スタイルガイド',
	navSpecification: '仕様',
	navGitHub: 'GitHub',
	pickerTheme: 'テーマ',
	pickerLocale: '言語',
	pickerTextSize: '文字サイズ',
	pickerShare: '共有',
	pickerShareCopyLink: 'リンクをコピー',
	pickerShareCopied: 'コピーしました',
	breadcrumb: 'パンくずリスト',
	breadcrumbChapters: '章',
	breadcrumbReference: '参照',
	onThisPage: 'このページの内容',
	headingAnchorPrefix: 'リンク先：',
	chapterNavigation: '章のナビゲーション',
	previous: '前へ',
	next: '次へ',
	editOnGitHub: 'GitHubでこのページを編集',
	sourceOfTruth: '本書が信頼できる唯一の情報源であり、このサイトはそれを表示するだけです。',
	siteFooter: 'サイトフッター',
	footerDescription:
		'保健・社会的ケア組織でデジタルサービスを届けるための、実践的なベストプラクティス・ハンドブック。執筆：Joel Parker Henderson。使用：',
	footerLilyLink: 'Lily Design System',
	footerGitHub: 'GitHub',
	footerGitLab: 'GitLab',
	footerCodeberg: 'Codeberg',
	footerSpecification: '仕様',
	notFoundHeading: 'ページが見つかりません',
	errorHeading: '問題が発生しました',
	notFoundBody: '',
	notFoundBodyEnd: 'にページはありません。本書で移動または名前が変更された可能性があります。',
	errorBodyFallback: 'ページを読み込めませんでした。',
	tryPrefix: '次をお試しください：',
	tryTableOfContents: '目次',
	tryGlossary: '用語集',
	tryOr: 'または',
	tryIndex: '索引'
};

/** @type {Record<string, typeof en>} */
const TABLES = {
	'en-gb': en,
	'en-us': en,
	'en-gb-oxendict': en,
	'en-001': en,
	'ar-001': ar,
	'cy-001': cyGb,
	'de-de': de,
	'ja-jp': ja,
	'zh-cn': zhCn,
	'es-001': es,
	'fr-001': fr,
	'hi-in': hi
};

/** Site chrome strings for one locale, falling back to English. */
export function stringsFor(locale) {
	return TABLES[locale] ?? en;
}
